import {
  InvalidIssueRelationTypeError,
  InvalidIssueStatusError,
  InvalidReactionTargetTypeError,
  IssueCommentNotFoundError,
  IssueDeleteStatusConflictError,
  IssueHasChildrenDeleteConflictError,
  IssueNotFoundError,
  IssueParentNotFoundError,
  IssueParentProjectMismatchError,
  IssueRelationAlreadyExistsError,
  IssueRelationNotFoundError,
  MilestoneNotFoundError,
  MissingIssueCommentFieldsError,
  MissingIssueCreateFieldsError,
  MissingIssueRelationFieldsError,
  MissingMilestoneTitleError,
  MissingReactionFieldsError,
  SelfIssueRelationError,
  SourceIssueNotFoundError,
  TargetIssueNotFoundError,
  TargetIssueProjectMismatchError,
} from '../../services/issue/errors';
import type { ErrorHttpEntry } from '../http-error-types';

export const issueErrorHttpEntries = [
  [MissingIssueCreateFieldsError, 400],
  [IssueParentNotFoundError, 400],
  [IssueParentProjectMismatchError, 400],
  [InvalidIssueStatusError, 400],
  [MissingIssueCommentFieldsError, 400],
  [InvalidReactionTargetTypeError, 400],
  [MissingReactionFieldsError, 400],
  [MissingMilestoneTitleError, 400],
  [MissingIssueRelationFieldsError, 400],
  [InvalidIssueRelationTypeError, 400],
  [SelfIssueRelationError, 400],
  [TargetIssueProjectMismatchError, 400],

  [IssueNotFoundError, 404],
  [IssueCommentNotFoundError, 404],
  [MilestoneNotFoundError, 404],
  [SourceIssueNotFoundError, 404],
  [TargetIssueNotFoundError, 404],
  [IssueRelationNotFoundError, 404],

  [IssueDeleteStatusConflictError, 409],
  [IssueHasChildrenDeleteConflictError, 409],
  [IssueRelationAlreadyExistsError, 409],
] satisfies readonly ErrorHttpEntry[];
